# -*- coding: utf-8 -*-
"""checkerboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nw71b6KJDXtKlTpBJn3vf3IdJTCrFMq-
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from scipy.optimize  import least_squares

from google.colab import files
from google.colab.patches import cv2_imshow

uploaded = files.upload()
img_path = list(uploaded.keys())[0]
candidate_patterns = [(5,5), (6,6), (4,4), (7,6), (6,7)]
square_size = 30.0
print(f"using img :{img_path}")
print("Will test candidate patterns:", candidate_patterns)

img = cv2.imread(img_path)
if img is None:
    raise ValueError("Image not found. Please upload Vaild file.")
original_ht, original_wd = img.shape[:2]
print(f"Original image dimensions: {original_wd} x {original_ht}")


scale_factor = 800 / original_wd
new_w = int(original_wd * scale_factor)
new_h = int(original_ht * scale_factor)
img_resized = cv2.resize(img, (new_w, new_h), interpolation=cv2.INTER_CUBIC)
gray = cv2.cvtColor(img_resized, cv2.COLOR_BGR2GRAY)
h, w = gray.shape
print(f"Resized image dimensions: {w} x {h}")

base_objp = None
imgpts = None
pattern_width, pattern_height = None, None
num_points = 0

best_ret = False
best_corners = None
best_pattern = None
flags = cv2.CALIB_CB_ADAPTIVE_THRESH | cv2.CALIB_CB_NORMALIZE_IMAGE

for pw, ph in candidate_patterns:
    ret, corners = cv2.findChessboardCorners(gray, (pw, ph), flags=flags)
    print(f"Trying {pw}x{ph} pattern: {'Success' if ret else 'Failed'} ({len(corners) if ret else 0} corners)")

    if ret and len(corners) == pw * ph:
        best_ret = ret
        best_corners = corners
        best_pattern = (pw, ph)
        pattern_width, pattern_height = pw, ph
        break

if not best_ret:
    print("No pattern detected automatically.")
    for pw, ph in candidate_patterns:
        ret, corners = cv2.findChessboardCorners(gray, (pw, ph), None)
        if ret and len(corners) == pw * ph:
            best_ret = ret
            best_corners = corners
            best_pattern = (pw, ph)
            pattern_width, pattern_height = pw, ph
            print(f"Success without flags for {pw}x{ph}")
            break

if not best_ret:
    raise ValueError("Chessboard corners not detected")

objp = np.zeros((pattern_width * pattern_height, 3), np.float32)
objp[:, :2] = np.mgrid[0:pattern_width, 0:pattern_height].T.reshape(-1, 2) * square_size
objp[:, 2] = 0  # Planar


criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
refined_corners = cv2.cornerSubPix(gray, best_corners, (11, 11), (-1, -1), criteria)
imgpts = refined_corners.reshape(-1, 2)
num_points = len(imgpts)


print(f"Best pattern detected: {pattern_width} x {pattern_height} inner corners ({num_points} points).")
print("Proceeding with RANSAC...")

H, mask = cv2.findHomography(objp[:, :2], imgpts, cv2.RANSAC, ransacReprojThreshold=5.0)
inliers = mask.ravel().astype(bool)
objp_in = objp[inliers]
imgpts_in = imgpts[inliers]
num_inliers = len(objp_in)
print(f"Detected {num_inliers} inlier points after RANSAC outlier removal.")

if num_inliers < 6:
    raise ValueError("Insufficient inlier points after RANSAC.")

cx_init = w / 2.0
cy_init = h / 2.0
fx_init = fy_init = max(w, h) * 0.8
K_init = np.array([[fx_init, 0, cx_init],
                   [0, fy_init, cy_init],
                   [0, 0, 1]], dtype=np.float32)
dist_init = np.array([0.0, 0.0, 0.0, 0.0, 0.0], dtype=np.float32)

success, rvec_init, tvec_init = cv2.solvePnP(objp_in, imgpts_in, K_init, dist_init)
if not success:
    raise ValueError("PnP initialization failed.")
R_init, _ = cv2.Rodrigues(rvec_init)

p0 = np.hstack([fx_init, fy_init, cx_init, cy_init, 0.0, 0.0,
                rvec_init.ravel(), tvec_init.ravel()])

print("Initialization complete.")

def cost_function(params, obj_pts, img_pts):
    fx, fy, cx, cy, k1, k2 = params[:6]
    rvec = params[6:9].reshape((3, 1))
    tvec = params[9:12].reshape((3, 1))

    K = np.array([[fx, 0, cx],
                  [0, fy, cy],
                  [0, 0, 1]], dtype=np.float64)
    dist = np.array([k1, k2, 0, 0, 0], dtype=np.float64)

    img_pts_proj, _ = cv2.projectPoints(obj_pts, rvec, tvec, K, dist)
    img_pts_proj = img_pts_proj.reshape(-1, 2)

    errors = (img_pts_proj - img_pts).ravel()
    return errors

lb = np.array([0.1*w, 0.1*w, 0.0, 0.0, -1.0, -1.0, -np.inf, -np.inf, -np.inf, -np.inf, -np.inf, -np.inf])

ub = np.array([10*w, 10*w, w, h, 1.0, 1.0, np.inf, np.inf, np.inf, np.inf, np.inf, np.inf])
bounds = (lb, ub)

res = least_squares(cost_function, p0, args=(objp_in, imgpts_in),
                    method='trf', bounds=bounds, verbose=1,
                    max_nfev=1000, ftol=1e-8, xtol=1e-8, gtol=1e-8)

params_est = res.x
print("Optimization converged:", res.success)
print("Final cost (sum of squared errors):", res.cost)

fx_est, fy_est, cx_est, cy_est, k1_est, k2_est = params_est[:6]
rvec_est = params_est[6:9].reshape((3, 1))
tvec_est = params_est[9:12].reshape((3, 1))

K_est = np.array([[fx_est, 0, cx_est],
                  [0, fy_est, cy_est],
                  [0, 0, 1]], dtype=np.float32)
dist_est = np.array([k1_est, k2_est, 0, 0, 0], dtype=np.float32)

print("\nEstimated Parameters:")
print(f"Camera Matrix K:\n{K_est}")
print(f"Radial Distortion [k1, k2]: [{k1_est:.6f}, {k2_est:.6f}]")
print(f"Rotation Vector rvec:\n{rvec_est}")
print(f"Translation Vector tvec:\n{tvec_est}")
print(f"Principal Point (cx, cy): ({cx_est:.2f}, {cy_est:.2f})")

mapx, mapy = cv2.initUndistortRectifyMap(K_est, dist_est, None, K_est, (w, h), cv2.CV_32FC1)
undist_img = cv2.remap(img_resized, mapx, mapy, interpolation=cv2.INTER_LINEAR)
cv2.imwrite('undistorted.jpg', undist_img)
files.download('undistorted.jpg')

imgpts_in_reshaped = imgpts_in.reshape(-1, 1, 2).astype(np.float32)

undist_imgpts = cv2.undistortPoints(imgpts_in_reshaped, K_est, dist_est, P=K_est)

undist_imgpts = undist_imgpts.reshape(-1, 2)

print("\nUndistorted Grid Corners (positions in undistorted image):")
for i, pt in enumerate(undist_imgpts[:10]):
    print(f"Point {i}: ({pt[0]:.2f}, {pt[1]:.2f})")
if len(undist_imgpts) > 10:
    print(f"... and {len(undist_imgpts)-10} more points.")

imgpts_reproj, _ = cv2.projectPoints(objp_in, rvec_est, tvec_est, K_est, dist_est)
imgpts_reproj = imgpts_reproj.reshape(-1, 2)

residuals = imgpts_in - imgpts_reproj
reproj_errors = np.sqrt(np.sum(residuals**2, axis=1))

mean_reproj_error = np.mean(reproj_errors)
print(f"\nReprojection Errors (first 10 points in pixels):")
for i, err in enumerate(reproj_errors[:10]):
    print(f"Point {i}: {err:.4f}")
print(f"Final Mean Reprojection Error: {mean_reproj_error:.4f} pixels")

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB))
plt.title('Original Distorted Image (Resized)')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(undist_img, cv2.COLOR_BGR2RGB))
plt.title(f'Undistorted Image (Mean Reproj. Error: {mean_reproj_error:.4f} px)')
plt.axis('off')
plt.tight_layout()
plt.show()

img_with_corners = cv2.drawChessboardCorners(img_resized, (pattern_width, pattern_height), refined_corners, best_ret)
plt.figure(figsize=(8, 6))
plt.imshow(cv2.cvtColor(img_with_corners, cv2.COLOR_BGR2RGB))
plt.title('Detected Corners on Resized Original Image')
plt.axis('off')
plt.show()